# Generated by Django 2.1.1 on 2018-09-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starwar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='homeworld',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
