# Generated by Django 2.1.1 on 2018-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwar', '0002_auto_20180929_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='edited',
            new_name='modified_on',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='edited',
            new_name='modified_on',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='edited',
            new_name='modified_on',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='edited',
            new_name='modified_on',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='edited',
        ),
        migrations.AddField(
            model_name='transport',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
