# Generated by Django 2.1.1 on 2018-09-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starwar', '0005_auto_20180929_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPlanet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starwar.Planet')),
            ],
        ),
        migrations.RemoveField(
            model_name='people',
            name='homeworld',
        ),
        migrations.RemoveField(
            model_name='species',
            name='homeworld',
        ),
        migrations.RemoveField(
            model_name='species',
            name='people',
        ),
        migrations.RemoveField(
            model_name='starship',
            name='pilots',
        ),
        migrations.RemoveField(
            model_name='starship',
            name='transport_ptr',
        ),
        migrations.RemoveField(
            model_name='userfilm',
            name='film',
        ),
        migrations.RemoveField(
            model_name='userfilm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userplanet',
            name='planet',
        ),
        migrations.RemoveField(
            model_name='userplanet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pilots',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='transport_ptr',
        ),
        migrations.RemoveField(
            model_name='film',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='film',
            name='planets',
        ),
        migrations.RemoveField(
            model_name='film',
            name='species',
        ),
        migrations.RemoveField(
            model_name='film',
            name='starships',
        ),
        migrations.RemoveField(
            model_name='film',
            name='vehicles',
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.DeleteModel(
            name='Starship',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.DeleteModel(
            name='UserFilm',
        ),
        migrations.DeleteModel(
            name='UserPlanet',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.AddField(
            model_name='savedfilm',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starwar.Film'),
        ),
    ]
